name: CodeBuild Runner POC
on: [push]
jobs:
  custom-container-test:
    runs-on:
      - codebuild-RossGhRunnerPoc-${{ github.run_id }}-${{ github.run_attempt }}
      - instance-size:small
      - image:linux-5.0
    steps:
      - run: mvn --version
      - run: echo "Hello World!"
