name: CodeBuild Runner POC
on: [push]
jobs:
  custom-container-test:
    runs-on:
      - codebuild-RossGhRunnerPoc-${{ github.run_id }}-${{ github.run_attempt }}
      # - instance-size:small
      # - image:501215020883.dkr.ecr.eu-central-1.amazonaws.com/gha-runner/ross-poc:latest
    steps:
      - run: echo "Hello World!"
